package main

var metric_templates = map[string]MetricTemplate{
	"BytesDownloaded": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "BytesDownloaded",
		Period:     "3600",
		Unit:       "None",
		Namespace:  "AWS/CloudFront",
		Id:         "test1",
		Stat:       "Average",
	},
	},
	"Requests": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "Requests",
		Period:     "3600",
		Unit:       "None",
		Namespace:  "AWS/CloudFront",
		Id:         "test1",
		Stat:       "Average",
	},
	},
	"TotalErrorRate": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "TotalErrorRate",
		Period:     "3600",
		Unit:       "None",
		Namespace:  "AWS/CloudFront",
		Id:         "test1",
		Stat:       "Average",
	},
	},
	"BucketSizeBytes": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "BucketSizeBytes",
		Period:     "3600",
		Unit:       "Bytes",
		Namespace:  "AWS/S3",
		Id:         "test1",
		Stat:       "Average",
	},
	},
	"NumberOfObjects": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "NumberOfObjects",
		Period:     "3600",
		Unit:       "Bytes",
		Namespace:  "AWS/S3",
		Id:         "test1",
		Stat:       "Average",
	},
	},
	"RequestCount": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "RequestCount",
		Period:     "3600",
		Unit:       "Count",
		Namespace:  "AWS/ELB",
		Id:         "test1",
		Stat:       "Sum",
	},
	},
	"EstimatedProcessedBytes": MetricTemplate{Metrictype: "CloudWatchMetrics", Template: CloudwatchMetricTemplate{
		Metricname: "EstimatedProcessedBytes",
		Period:     "3600",
		Unit:       "Bytes",
		Namespace:  "AWS/ELB",
		Id:         "test1",
		Stat:       "Average",
	},
	},
	"CoreCount": MetricTemplate{Metrictype: "CustomMetrics", Template: CustomMetricTemplate{
		Metricname: "CoreCount",
	},
	},
	"VCpuCount": MetricTemplate{Metrictype: "CustomMetrics", Template: CustomMetricTemplate{
		Metricname: "VCpuCount",
	},
	},
	"Size": MetricTemplate{Metrictype: "CustomMetrics", Template: CustomMetricTemplate{
		Metricname: "Size",
	},
	},
}
